### ISSUE TITLE
Wrong file path of inheritance & benchmarks plot in docs

### ISSUE THREAD

**Issue by Abinashbunty** [Quantum-Optics-LKB/NLSE#6]
This is with reference to the ongoing review of the paper in openjournals/joss-reviews#6607

The plot for benchmarks in the docs is not rendered due to wrong file path. The page is https://quantum-optics-lkb.github.io/NLSE/installation/

At the extreme end, the image should be https://github.com/Quantum-Optics-LKB/NLSE/blob/main/img/benchmarks.png

**Comment by Abinashbunty** [comment]
In continuation, the inheritance image is also not rendered correctly due to path error. It should be https://github.com/Quantum-Optics-LKB/NLSE/blob/main/img/inheritance_graph.png on the page https://quantum-optics-lkb.github.io/NLSE/structure_and_inheritance/

**Comment by taladjidi** [comment]
Fixed ! 👍
